# Generated by Django 4.2.30 on 2026-07-01 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField()),
                ("drive_url", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("abbr", models.CharField(max_length=10)),
                ("emoji", models.CharField(default="📚", max_length=10)),
                ("degree", models.CharField(max_length=60)),
                ("description", models.TextField()),
                ("drive_url", models.URLField(blank=True)),
                ("color", models.CharField(default="#0c1b33", max_length=7)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Faculties",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("past-questions", "📄 Past Questions"),
                            ("lecture-notes", "📝 Lecture Notes"),
                            ("textbook", "📚 Textbook"),
                            ("slides", "🎞️ Slides"),
                            ("lab-manual", "🧪 Lab Manual / Report"),
                            ("outline", "📋 Course Outline / Syllabus"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (100, "100 Level"),
                            (200, "200 Level"),
                            (300, "300 Level"),
                            (400, "400 Level"),
                            (500, "500 Level"),
                            (600, "600 Level"),
                        ]
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        blank=True, help_text="e.g. 2023/2024", max_length=20
                    ),
                ),
                ("drive_url", models.URLField(help_text="Google Drive sharing link")),
                (
                    "uploaded_by",
                    models.CharField(
                        help_text="Submitter name or 'Anonymous'", max_length=150
                    ),
                ),
                (
                    "contact",
                    models.EmailField(
                        blank=True, help_text="Optional — for follow-up", max_length=254
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "⏳ Pending Review"),
                            ("approved", "✅ Approved — Live"),
                            ("rejected", "❌ Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "admin_note",
                    models.TextField(
                        blank=True, help_text="Internal note (not shown to students)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="core.department",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="core.faculty",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 star"),
                            (2, "2 stars"),
                            (3, "3 stars"),
                            (4, "4 stars"),
                            (5, "5 stars"),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="core.resource",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="department",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="core.faculty",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("faculty", "slug")},
        ),
    ]
