# Generated by Django 4.2.30 on 2026-07-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Upload PDF, DOCX, PPTX etc. (max 20MB)",
                null=True,
                upload_to="materials/",
            ),
        ),
    ]
