# Generated by Django 4.2.30 on 2026-07-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_resource_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="drive_url",
            field=models.URLField(
                blank=True, help_text="Google Drive sharing link (optional)"
            ),
        ),
    ]
