# Generated by Django 4.2.30 on 2026-07-03 18:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_resource_drive_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="file",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Upload PDF, DOCX, PPTX etc. (max 20MB)",
                max_length=255,
                null=True,
                verbose_name="file",
            ),
        ),
    ]
