# Generated by Django 4.2.30 on 2026-07-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_resource_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="file",
        ),
        migrations.AddField(
            model_name="resource",
            name="file_url",
            field=models.URLField(
                blank=True, help_text="Auto-filled by Cloudinary on upload"
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="drive_url",
            field=models.URLField(blank=True, help_text="Google Drive link (optional)"),
        ),
    ]
